#version: '3.8'

services:
  django:
    build: ./django
    container_name: django_app
    restart: unless-stopped
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
    volumes:
      - ./django/app:/app/app
#      - static_volume:/app/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      - postgres
    expose:
      - "8000"

  postgres:
    image: postgres:15
    container_name: postgres_app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

#  mongodb:
#    image: mongo:7
#    container_name: mongodb_app
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#    volumes:
#      - ./mongo_data:/data/db
#    networks:
#      - internal
#
#  redis:
#    image: redis:7
#    container_name: redis_app
#    restart: always
#    command: ["redis-server", "--appendonly", "yes"]
#    volumes:
#      - ./redis_data:/data
#    networks:
#      - internal
#
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq_app
#    restart: always
#    environment:
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
#    ports:
#      - "15672:15672"
#    networks:
#      - internal

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_app
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      N8N_LOG_LEVEL: info
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_SECURE_COOKIE: false

      N8N_PORT: 5678
      N8N_PROTOCOL: https
      N8N_HOST: n8n.bezzze.ru

      VUE_APP_PUBLIC_PATH: /     # важно!

      WEBHOOK_URL: https://n8n.bezzze.ru/
      WEBHOOK_TUNNEL_URL: https://n8n.bezzze.ru/

      N8N_EDITOR_BASE_URL: https://n8n.bezzze.ru/
      N8N_PUBLIC_URL: https://n8n.bezzze.ru/

      N8N_ENDPOINT_WEBHOOK: webhook
      N8N_ENDPOINT_WEBHOOK_TEST: webhook-test

      DB_TYPE: postgres
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379

    volumes:
      - ./n8n_data:/home/node
      - ./n8n-local-files:/files
    depends_on:
      postgres:
        condition: service_healthy
#      redis:
#        condition: service_started
#      rabbitmq:
#        condition: service_started
#      mongodb:
#        condition: service_started
    networks:
      - internal
    expose:
      - "5678"

  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - n8n
      - django
    networks:
      - internal

volumes:
#  static_volume:
  postgres_data:
#  mongo_data:
#  redis_data:
  n8n_data:
  n8n-local-files:

networks:
  internal:
    driver: bridge


